package com.tradingreporting.api.security;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class PasswordHasherTest {

    private final PasswordHasher hasher = new PasswordHasher();

    @Test
    void verifiesAKnownPasslibPbkdf2Sha256Hash() {
        // Generated by Python: passlib.hash.pbkdf2_sha256.using(rounds=29000).hash("CorrectHorseBattery1!")
        String passlibHash = "$pbkdf2-sha256$29000$oNQ6xxjjnHPu3RujlNLaew$MTwGewwuo3qGIA/plCQcWynEIlyWG8ANn3w7T4YD01k";

        assertThat(hasher.verify("CorrectHorseBattery1!", passlibHash)).isTrue();
        assertThat(hasher.verify("wrong-password", passlibHash)).isFalse();
    }

    @Test
    void hashRoundTripsThroughItsOwnVerify() {
        String hash = hasher.hash("s3cret-Value!");

        assertThat(hash).startsWith("$pbkdf2-sha256$29000$");
        assertThat(hasher.verify("s3cret-Value!", hash)).isTrue();
        assertThat(hasher.verify("not-it", hash)).isFalse();
    }

    @Test
    void rejectsMalformedHashesInsteadOfThrowing() {
        assertThat(hasher.verify("anything", "not-a-real-hash")).isFalse();
        assertThat(hasher.verify("anything", null)).isFalse();
    }
}
