namespace backend_dotnet;
using System.ComponentModel.DataAnnotations;
public record LoginRequest([Required] string Username, [Required] string Password); public record MockCallbackRequest([Required] string Username); public record TokenResponse(string AccessToken, string TokenType);
public record TradeInput(DateOnly TradeDate, [Required] string Account, [Required] string Instrument, [RegularExpression("BUY|SELL")] string Side, decimal Quantity, decimal Price, string Currency = "USD", string Status = "BOOKED", string? Notes = null);
public record TradeUpdate(DateOnly TradeDate, string Account, string Instrument, [RegularExpression("BUY|SELL")] string Side, decimal Quantity, decimal Price, string Currency, string Status, string? Notes, [Range(1, int.MaxValue)] int ExpectedVersion) : TradeInput(TradeDate, Account, Instrument, Side, Quantity, Price, Currency, Status, Notes);
public record DailyRowUpdate(string Id, [Range(1, int.MaxValue)] int ExpectedVersion, decimal Delta, decimal Gamma, decimal Theta, decimal Vega, decimal Pnl); public record DailySaveRequest(DateOnly BusinessDate, [Required, MinLength(1)] List<DailyRowUpdate> Rows);
public record TradeEntryRow(string? Id, [Required, MaxLength(100)] string Name, [Required, MaxLength(30)] string Code, [Required, MinLength(1), MaxLength(50)] List<decimal> Values, bool Locked = false, [Range(1, int.MaxValue)] int Version = 1);
public record TradeEntrySaveRequest(DateOnly BusinessDate, [Required, MinLength(1), MaxLength(500)] List<TradeEntryRow> Rows);
public record TradeDto(string Id, DateOnly TradeDate, string Account, string Instrument, string Side, decimal Quantity, decimal Price, string Currency, string Status, string? Notes, int Version, string CreatedById, DateTime CreatedAt, DateTime UpdatedAt, bool Locked, string? LockedById, string? LockedByDisplayName, DateTime? LockedAt, DateTime? LockExpiresAt) { public static TradeDto From(Trade t) => new(t.Id, t.TradeDate, t.Account, t.Instrument, t.Side, t.Quantity, t.Price, t.Currency, t.Status, t.Notes, t.Version, t.CreatedById, t.CreatedAt, t.UpdatedAt, t.Locked, t.LockedById, t.LockedByDisplayName, t.LockedAt, t.LockExpiresAt); }
public record DailyEntryDto(string Id, DateOnly BusinessDate, string BusinessId, string Name, string Code, decimal Delta, decimal Gamma, decimal Theta, decimal Vega, decimal Pnl, int Version, bool Locked, string? LockedById, string? LockedByDisplayName, DateTime? LockedAt, DateTime? LockExpiresAt, DateTime UpdatedAt) { public static DailyEntryDto From(DailyTradeEntry e) => new(e.Id, e.BusinessDate, e.BusinessId, e.Business.Name, e.Business.Code, e.Delta, e.Gamma, e.Theta, e.Vega, e.Pnl, e.Version, e.Locked, e.LockedById, e.LockedByDisplayName, e.LockedAt, e.LockExpiresAt, e.UpdatedAt); }
public record LockDto(string Id, bool Locked, string? LockedById, string? LockedByDisplayName, DateTime? LockedAt, DateTime? LockExpiresAt, int Version) { public static LockDto From(Trade t) => new(t.Id, t.Locked, t.LockedById, t.LockedByDisplayName, t.LockedAt, t.LockExpiresAt, t.Version); public static LockDto From(DailyTradeEntry e) => new(e.Id, e.Locked, e.LockedById, e.LockedByDisplayName, e.LockedAt, e.LockExpiresAt, e.Version); }
